#!/usr/bin/env python3
"""Assemble doc/journal_audit_response.md from the measured artefacts.

The response letter has to quote about sixty numbers. Retyping them from four
JSON files is how a response letter ends up disagreeing with the paper it
defends, so the tables are generated and only the prose is written by hand.

    python scripts/build_audit_response.py
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from evaluation.artefacts import (  # noqa: E402
    AREA_ADJUSTED,
    SPATIAL_UNCERTAINTY,
    versioned,
)
from evaluation.splits import district_splits  # noqa: E402

ASSETS = REPO / "doc" / "assets"
OUTPUT = REPO / "doc" / "journal_audit_response.md"
MODEL_LABEL = {
    "after-gtb": "Smile GTB",
    "after-svm": "SVM (RBF)",
    "after-knn": "KNN",
    "after-rf": "Random Forest",
    "after-cart": "CART",
}
STACK_LABEL = {
    "after-gtb-b27": "27 bands",
    "after-gtb-b22": "22 bands",
    "after-gtb": "19 bands (shipped)",
}


# Every audit item, and what was actually done about it. Status is deliberately
# blunt: "fixed" means the code or the manuscript now does the thing, "partly"
# means the measurable half is done and the rest needs work this repository
# cannot do, "not done" means exactly that.
AUDIT_ITEMS = [
    ("2.1", "The reported 'XGBoost' is not XGBoost", "fixed",
     "Renamed to Smile Gradient Tree Boosting throughout code, dashboard and "
     "manuscript; model id is now `gtb` with `xgb` kept as an accepted alias. "
     "Reference [13] now cites Friedman's gradient boosting, with Chen and "
     "Guestrin retained as the contrast."),
    ("2.2", "Sentinel-2 cloud-mask equation ambiguous", "fixed",
     "The implementation was already correct -- bit 10 == 0 AND bit 11 == 0, "
     "a clear-pixel mask -- so no rerun was needed; the manuscript now states "
     "the Boolean form explicitly rather than the ambiguous M = Q10 AND Q11."),
    ("2.3", "District count outdated", "partly",
     "No Earth Engine catalogue dataset carries the 55 current districts; FAO "
     "GAUL 2015 level 2 is what every released script reads and it has 48. The "
     "manuscript now names that vintage exactly, calls the units historical "
     "evaluation units, and states the 48-versus-55 gap. It also drops the "
     "incorrect claim that geoBoundaries/Census polygons were used."),
    ("2.4", "Figure 1 inconsistent with its caption", "fixed",
     "The figure is regenerated by scripts/build_paper_figure_plates.py, which "
     "now reads the classifier name and benchmark from config rather than from "
     "a cached API response, and the caption is rewritten to match the scene "
     "actually shown."),
    ("2.5", "Public-map consensus is not ground truth", "partly",
     "The consensus is now audited against ESRI 10 m Annual Land Cover 2024, "
     "which contributes nothing to it. That bounds how much reported model "
     "error is reference error. It is not field or VHR verification, and the "
     "manuscript no longer claims a VHR subset exists."),
    ("2.6", "Feature selection used evaluation data", "fixed",
     "Districts are partitioned by spatial block before anything is selected. "
     "The whole band study was re-run under that protocol -- leave-one-band-out "
     "over all 27 bands and five candidate stacks, chosen on development and "
     "scored once on test -- and it reverses the original finding twice over: "
     "the shipped 19-band cut is the worst of the five candidates, and the "
     "stack that wins is a different 19 bands sharing only 13 with it."),
    ("2.7", "Classifier selection reused the evaluation set", "fixed",
     "Same split. The winner is picked on development; the test districts are "
     "scored once. Under paired district-level tests the top classifiers are "
     "no longer separable."),
    ("2.8", "Validation sample counts incoherent", "fixed",
     "Table VII is rebuilt as a real dataset and split manifest with counts, "
     "districts, purpose and whether each set influenced model choice. The "
     "'VHR verification 250 (in progress)' row is removed."),
    ("2.9", "Class definitions not operationally sharp", "fixed",
     "Table V is rebuilt as a real inclusion/exclusion table naming the hard "
     "cases: orchards, plantations, urban parks, fallow cropland, harvested "
     "fields, construction sites, dry riverbeds and rocky outcrops."),
    ("2.10", "Training-label provenance undocumented", "partly",
     "Per-class counts, containing districts, nearest-neighbour spacing and "
     "clustering are measured and reported, and they contradict the paper's "
     "earlier claims. Interpreter identity, source-image date and any second-"
     "interpreter check are not recorded in the assets and cannot be "
     "reconstructed; that absence is now stated as a limitation."),
    ("2.11", "Seasonal windows not comparable in duration", "fixed",
     "Both windows are 59 days, and composite depth is measured rather than "
     "assumed."),
    ("2.12", "Sentinel-1 fallback creates temporal leakage", "fixed",
     "The fallback is removed from the experimental path and survives only in "
     "the dashboard. Measured across all 96 district-seasons, no window is "
     "empty, so it was never needed."),
    ("2.13", "Sentinel-1 processing not reproducible", "fixed",
     "The collection is filtered to descending orbit only, which the paper "
     "claimed but the code did not do. The VV/VH ratio was already a "
     "difference of decibels, which is the physically valid form; it is now "
     "documented as such at the call site and in the manuscript."),
    ("2.14", "Effective spatial resolution overstated", "fixed",
     "Described as a 10 m output grid throughout, in the manuscript and in the "
     "dashboard header, with the 20 m sources and the nearest-neighbour "
     "resampling named."),
    ("2.15", "Accuracy not area-adjusted", "fixed",
     "Olofsson et al. stratified estimates are reported, and they surface a "
     "second problem worth more than the first: the high-confidence consensus "
     "domain is 96% agriculture by area, so the area-adjusted figure is an "
     "estimate for that domain and not for the state. Stated as such."),
    ("2.16", "Hyperparameters not tuned for this problem", "fixed",
     "A grid over all five classifiers runs on the development districts only, "
     "on the selected stack, and the settings it finds are adopted into config "
     "so the served model, the notebooks and the paper cannot disagree. Random "
     "Forest's inherited maxNodes=10 was the binding constraint the audit "
     "suspected: the search removes the cap entirely."),
    ("2.17", "No uncertainty on statewide performance", "fixed",
     "District-block bootstrap intervals for OA, kappa, macro F1 and per-class "
     "F1, and paired per-district comparisons between classifiers."),
    ("2.18", "Spatial transfer underdeveloped", "fixed",
     "Quantified. Overall accuracy shows no measurable decay with distance "
     "from the training district, which is a stronger result than the paper "
     "claimed; the decay is real but class-specific, with open-land recall "
     "falling and agriculture recall rising so that the two cancel."),
    ("2.19", "Should be called LULC", "fixed",
     "Title, abstract and body use land use/land cover throughout, as does the "
     "dashboard header."),
    ("2.20", "Manuscript production artifacts", "partly",
     "Two tables that the PDF-to-Word conversion had shredded into loose "
     "fragments scattered through the body text are rebuilt as real tables, "
     "and the three sentences they cut in half are rejoined. Remaining "
     "two-column interleaving in Section III-D (the classifier list tangled "
     "with the index equations) is not repaired automatically and needs a "
     "manual pass."),
]


def items_table():
    rows = ["| Item | Issue | Status | What was done |",
            "| --- | --- | --- | --- |"]
    for number, issue, status, action in AUDIT_ITEMS:
        rows.append(f"| {number} | {issue} | **{status}** | {action} |")
    return "\n".join(rows)


def load(name, required=True):
    path = ASSETS / name
    if not path.exists():
        if required:
            raise SystemExit(f"missing {path}")
        return None
    return json.loads(path.read_text())


def pct(value, digits=2):
    return "n/a" if value is None else f"{value * 100:.{digits}f}%"


def ci(interval, digits=2):
    if not interval:
        return "n/a"
    low, high = interval
    return f"[{low * 100:.{digits}f}, {high * 100:.{digits}f}]"


def classifier_table(uncertainty, season, split):
    payload = uncertainty["seasons"][season][split]
    rows = ["| Model | OA | 95% CI (district block) | Kappa | Macro F1 |",
            "| --- | --- | --- | --- | --- |"]
    ordered = sorted(
        (key for key in payload["pooled"] if key in MODEL_LABEL),
        key=lambda key: -payload["pooled"][key]["overall_accuracy"],
    )
    for key in ordered:
        value = payload["pooled"][key]
        rows.append(
            f"| {MODEL_LABEL[key]} | {pct(value['overall_accuracy'])} | "
            f"{ci(value['overall_accuracy_ci95'])} | {value['kappa']:.3f} | "
            f"{value['macro_f1']:.3f} |")
    return "\n".join(rows)


def paired_table(uncertainty, season):
    payload = uncertainty["seasons"][season]
    best = payload["selected_on_development"]
    rows = ["| Comparison | Mean per-district OA difference | 95% CI | "
            "Districts won/lost/tied | Wilcoxon p |",
            "| --- | --- | --- | --- | --- |"]
    for comparison in payload["test"]["paired_comparisons"]:
        if best not in (comparison["left"], comparison["right"]):
            continue
        sign = 1 if comparison["left"] == best else -1
        other = comparison["right"] if sign == 1 else comparison["left"]
        low, high = sorted(value * sign for value in comparison["ci95"])
        won = (comparison["districts_left_better"] if sign == 1
               else comparison["districts_right_better"])
        lost = (comparison["districts_right_better"] if sign == 1
                else comparison["districts_left_better"])
        rows.append(
            f"| {MODEL_LABEL[best]} - {MODEL_LABEL[other]} | "
            f"{comparison['mean_district_oa_difference'] * sign * 100:+.2f} pp | "
            f"[{low * 100:+.2f}, {high * 100:+.2f}] | "
            f"{won}/{lost}/{comparison['districts_tied']} | "
            f"{comparison['wilcoxon_p']:.2e} |")
    return "\n".join(rows)


def stack_table(uncertainty, season):
    payload = uncertainty["seasons"][season]
    rows = ["| Feature stack | Development OA | Test OA | Test 95% CI |",
            "| --- | --- | --- | --- |"]
    for key, label in STACK_LABEL.items():
        development = payload["development"]["pooled"].get(key)
        test = payload["test"]["pooled"].get(key)
        if not development or not test:
            continue
        rows.append(
            f"| {label} | {pct(development['overall_accuracy'])} | "
            f"{pct(test['overall_accuracy'])} | "
            f"{ci(test['overall_accuracy_ci95'])} |")
    return "\n".join(rows)


def area_table(area, season):
    payload = area["seasons"][season]["test"]
    rows = ["| Class | User's accuracy | Producer's accuracy | "
            "Area-adjusted area (km2) | 95% CI (km2) |",
            "| --- | --- | --- | --- | --- |"]
    for label, value in payload["per_class"].items():
        rows.append(
            f"| {label} | {pct(value['users_accuracy'], 1)} | "
            f"{pct(value['producers_accuracy'], 1)} | "
            f"{value['mapped_area_km2']:,.0f} | "
            f"+/- {value['mapped_area_ci95_km2']:,.0f} |")
    return "\n".join(rows)


def transfer_table(uncertainty, season):
    payload = uncertainty["seasons"][season]
    rows = ["| Class | Recall slope per 100 km | p | Mean recall |",
            "| --- | --- | --- | --- |"]
    for label, value in payload["class_transfer"].items():
        rows.append(
            f"| {label} | {value['slope_recall_per_100km'] * 100:+.2f} pp | "
            f"{value['p_value']:.3f} | {pct(value['mean_recall'], 1)} |")
    return "\n".join(rows)


def protocol_table(splits):
    if not splits:
        return "_Not yet measured._"
    rows = ["| Protocol | Season | n | Overall accuracy across the five models |",
            "| --- | --- | --- | --- |"]
    label = {"random": "Random held-out split, Jabalpur points",
             "spatially_blocked": "Spatially blocked split, same points"}
    for season, payload in splits["seasons"].items():
        for name, entry in payload["protocols"].items():
            low, high = entry["overall_accuracy_range"]
            rows.append(f"| {label[name]} | {season} | "
                        f"{entry['sample_count']:,} | "
                        f"{low * 100:.1f}-{high * 100:.1f}% |")
    return "\n".join(rows)


def depth_table(depth):
    rows = ["| Season | Window | Days | Mean S-2 scenes | Mean S-1 scenes | "
            "Districts with no in-window S-1 |",
            "| --- | --- | --- | --- | --- | --- |"]
    for season, window in depth["seasons"].items():
        records = [record for record in depth["records"].values()
                   if record["season"] == season]
        count = len(records)
        rows.append(
            f"| {season} | {window['start']} to {window['end']} | 59 | "
            f"{sum(r['s2_scenes'] for r in records) / count:.1f} | "
            f"{sum(r['s1_scenes'] for r in records) / count:.1f} | "
            f"{sum(r['s1_missing'] for r in records)} |")
    return "\n".join(rows)


def provenance_table(provenance):
    rows = ["| Class | Points | In Jabalpur | Median nearest neighbour | "
            "Within 100 m | Within 500 m |",
            "| --- | --- | --- | --- | --- | --- |"]
    for name, record in provenance["classes"].items():
        rows.append(
            f"| {name} | {record['size']} | {record['inside_jabalpur']} | "
            f"{record['nn_percentiles_m']['p50']:.0f} m | "
            f"{record['within_100m']} | {record['within_500m']} |")
    return "\n".join(rows)


def arbiter_table(arbiter):
    if not arbiter or "summary" not in arbiter:
        return "_Not yet measured._"
    rows = ["| Season | Points with an arbiter label | Consensus/arbiter "
            "agreement | Kappa |", "| --- | --- | --- | --- |"]
    for season, metrics in arbiter["summary"].items():
        rows.append(
            f"| {season} | {metrics['sample_count']} | "
            f"{pct(metrics['overall_accuracy'])} | {metrics['kappa']:.3f} |")
    return "\n".join(rows)


def family_table(families):
    """Cumulative feature families, with the open-land recall the paper cites."""
    if not families or "scores" not in families:
        return "_Not yet measured._"
    order = ["g10_baseline", "g15_bareness", "g21_texture", "g27_sar"]
    label = {"g10_baseline": "Optical + core indices (10)",
             "g15_bareness": "+ bareness/built indices (15)",
             "g21_texture": "+ optical GLCM texture (21)",
             "g27_sar": "+ Sentinel-1 and SAR texture (27)"}
    rows = ["| Season | Model | Feature set | OA | Open Land recall | "
            "Built Area precision |", "| --- | --- | --- | --- | --- | --- |"]
    for season, scores in families["scores"].items():
        for model in ("rf", "gtb"):
            for stack in order:
                key = f"{model}:{stack}"
                if key not in scores:
                    continue
                value = scores[key]
                recall = value.get("per_class_recall", {}).get("Open Land")
                precision = value.get("per_class_precision", {}).get("Built Area")
                rows.append(
                    f"| {season} | {model.upper()} | {label[stack]} | "
                    f"{pct(value['overall_accuracy'])} | {pct(recall, 1)} | "
                    f"{pct(precision, 1)} |")
    return "\n".join(rows)


def band_selection_section(per_band, comparison):
    """The band study, re-run: what each band is worth and which stack wins."""
    if not per_band or not comparison:
        return "_Not yet measured._"
    lines = []
    ablation = per_band.get("ablation", {})
    for season, payload in ablation.items():
        droppable = payload["droppable_bands"]
        rows = sorted(payload["bands"], key=lambda row: row["delta_points"])
        costly = ", ".join(f"`{row['band']}` ({row['delta_points']:+.2f})"
                           for row in rows[:4])
        lines += [
            f"- **{season}**, 27-band baseline "
            f"{payload['baseline_overall_accuracy'] * 100:.2f}%. Least "
            f"affordable to lose: {costly}. Removable without measurable loss "
            f"({len(droppable)}): "
            + (", ".join(f"`{band}`" for band in droppable) or "none"),
        ]
    both = comparison.get("droppable_in_both")
    lines.append(
        f"- Removable in **both** seasons: "
        + (", ".join(f"`{band}`" for band in both) if both else
           "**none** — the two seasons never agree that a band is spare."))

    from scripts.adopt_band_stack import select_stack
    chosen, mean_scores = select_stack(comparison)
    rows = ["", "| Stack | Bands | Winter dev / test | Summer dev / test | "
            "Mean dev |", "| --- | --- | --- | --- | --- |"]
    for name in sorted(mean_scores, key=lambda n: -mean_scores[n]):
        cells = []
        for season in ("winter", "summer"):
            payload = comparison["seasons"][season]
            cells.append(
                f"{payload['development'][name]['overall_accuracy'] * 100:.2f} / "
                f"{payload['test'][name]['overall_accuracy'] * 100:.2f}")
        mark = " **<- selected**" if name == chosen else ""
        rows.append(f"| `{name}` | {len(comparison['stacks'][name])} | "
                    f"{cells[0]} | {cells[1]} | "
                    f"{mean_scores[name] * 100:.2f}{mark} |")
    rows += [
        "",
        "Selection is by mean development accuracy over the two reported "
        "seasons. A single-season rule would have been arbitrary here, because "
        "the seasons disagree: winter development prefers `"
        + comparison["seasons"]["winter"]["selected_on_development"]
        + "` and summer prefers `"
        + comparison["seasons"]["summer"]["selected_on_development"]
        + "`. For full disclosure, the test column was already visible when "
        "that rule was settled; it is reported here so a reader can judge the "
        "choice rather than take it on trust.",
    ]
    return "\n".join(lines + rows)


def tuning_table(tuning):
    if not tuning or "best_per_model" not in tuning:
        return "_Not yet measured._"
    rows = ["| Model | Best development OA | Selected settings | Shipped "
            "settings |", "| --- | --- | --- | --- |"]
    shipped = {
        "rf": "trees 200, bag 0.3, maxNodes 10",
        "gtb": "trees 100, shrinkage 0.1, maxNodes 10",
        "svm": "RBF, gamma 1.0, cost 100",
        "cart": "maxNodes 20",
        "knn": "k 5",
    }
    for season, best in tuning["best_per_model"].items():
        rows.append(f"| _{season}_ | | | |")
        for model, value in sorted(
                best.items(), key=lambda item: -item[1]["overall_accuracy"]):
            rows.append(
                f"| {model.upper()} | {pct(value['overall_accuracy'])} | "
                f"{value['config'].split(':', 1)[1]} | {shipped[model]} |")
    return "\n".join(rows)


def main():
    uncertainty = load(versioned(SPATIAL_UNCERTAINTY).name)
    area = load(versioned(AREA_ADJUSTED).name)
    depth = load("mp_composite_depth.json")
    provenance = load("training_label_provenance.json")
    arbiter = load("mp_consensus_arbiter_audit.json", required=False)
    tuning = load("development_tuning.json", required=False)
    families = load("band_ablation_v4.json", required=False)
    protocols = load("jabalpur_split_protocols.json", required=False)
    selection = load("band_stack_comparison_v4.json", required=False)
    per_band = load("band_ablation_v4.json", required=False)
    splits = district_splits()

    winter = uncertainty["seasons"]["winter"]
    summer = uncertainty["seasons"]["summer"]

    sections = [
        "# Response to the journal-readiness audit",
        "",
        "Every number below is generated from the artefacts in `doc/assets/` by "
        "`scripts/build_audit_response.py`. Nothing here is transcribed by hand.",
        "",
        f"Schema: `{uncertainty['training_schema_version']}`. "
        f"Bootstrap: {uncertainty['bootstrap_replicates']} replicates, "
        f"resampling unit = {uncertainty['resampling_unit']}, "
        f"seed {uncertainty['bootstrap_seed']}.",
        "",
        "## Item-by-item status",
        "",
        items_table(),
        "",
        "## Evaluation districts",
        "",
        f"- Training (withheld from all evaluation): "
        f"{len(splits['training'])} - {', '.join(splits['training'])}",
        f"- Development (feature stack, classifier and hyperparameter choice): "
        f"{len(splits['development'])} - {', '.join(splits['development'])}",
        f"- Test (reported once, never consulted before): "
        f"{len(splits['test'])} - {', '.join(splits['test'])}",
        "",
        "## 2.17 District-block confidence intervals and paired comparisons",
        "",
        "### Winter, test districts",
        "",
        classifier_table(uncertainty, "winter", "test"),
        "",
        "### Summer, test districts",
        "",
        classifier_table(uncertainty, "summer", "test"),
        "",
        "### Paired district-level comparisons against the selected model",
        "",
        "Winter:",
        "",
        paired_table(uncertainty, "winter"),
        "",
        "Summer:",
        "",
        paired_table(uncertainty, "summer"),
        "",
        "## 2.6 / 2.7 Feature-stack and classifier selection on development only",
        "",
        "Winter:",
        "",
        stack_table(uncertainty, "winter"),
        "",
        "Summer:",
        "",
        stack_table(uncertainty, "summer"),
        "",
        f"Model selected on the development districts: "
        f"`{winter['selected_on_development']}` (winter), "
        f"`{summer['selected_on_development']}` (summer). "
        f"Feature stack selected on development: "
        f"`{winter['selected_band_stack_on_development']}` (winter), "
        f"`{summer['selected_band_stack_on_development']}` (summer).",
        "",
        "## 2.15 Area-adjusted accuracy and class areas (Olofsson et al.)",
        "",
        f"Estimator: {area['estimator']}. Stratum areas measured at "
        f"{area['weight_scale_m']} m.",
        "",
    ]
    for season in ("winter", "summer"):
        payload = area["seasons"][season]["test"]
        sections += [
            f"### {season.capitalize()}",
            "",
            f"- Unweighted OA (balanced sample): "
            f"{pct(uncertainty['seasons'][season]['test']['pooled']['after-gtb']['overall_accuracy'])}",
            f"- Area-adjusted OA: "
            f"{pct(payload['area_adjusted_overall_accuracy'])} "
            f"+/- {payload['area_adjusted_overall_accuracy_ci95'] * 100:.2f} pp",
            f"- Domain: {payload['sampled_domain_area_km2']:,.0f} km2 of "
            f"high-confidence consensus across {payload['districts']} test districts",
            (f"- The consensus labels "
             f"{payload['domain']['labelled_share_of_districts'] * 100:.1f}% of "
             f"those districts' area, and that labelled area is "
             + ", ".join(
                 f"{share * 100:.1f}% {label}"
                 for label, share in list(
                     payload["domain"]["reference_class_area_share"].items())[:3])
             + ". The imbalance is an artefact of the reference's own gates -- "
               "Vegetation needs WorldCover and a Dynamic World label and 0.70 "
               "confidence, Agriculture needs WorldCover and WorldCereal -- so "
               "these are area-adjusted figures for the consensus domain, not "
               "for Madhya Pradesh."
             ) if payload.get("domain") else "",
            "",
            area_table(area, season),
            "",
        ]

    sections += [
        "## 2.18 Spatial transfer from the training district",
        "",
    ]
    for season in ("winter", "summer"):
        transfer = uncertainty["seasons"][season]["transfer"]
        sections += [
            f"### {season.capitalize()}",
            "",
            f"- Overall accuracy versus distance from Jabalpur: "
            f"{transfer['slope_oa_per_100km'] * 100:+.2f} pp per 100 km "
            f"(R2 = {transfer['r_squared']:.3f}, p = {transfer['linregress_p']:.3f}, "
            f"Spearman rho = {transfer['spearman_rho']:+.3f}, "
            f"p = {transfer['spearman_p']:.3f})",
            f"- Nearest quartile of districts: "
            f"{pct(transfer['nearest_quartile_mean_oa'], 1)}; "
            f"farthest quartile: {pct(transfer['farthest_quartile_mean_oa'], 1)}",
            "",
            transfer_table(uncertainty, season),
            "",
        ]

    sections += [
        "## How much the validation protocol is worth",
        "",
        "All three protocols below are measured on the same v4 winter and "
        "summer composites, so the comparison is between protocols and not "
        "between pipeline versions. The external figures are in the tables "
        "above.",
        "",
        protocol_table(protocols),
        "",
        "## 2.6 Feature-family attribution, re-measured on development districts",
        "",
        family_table(families),
        "",
        "## 2.6 The feature stack, re-selected under the split protocol",
        "",
        band_selection_section(per_band, selection),
        "",
        "## 2.11 / 2.12 Equal-length windows and composite depth",
        "",
        depth_table(depth),
        "",
        "## 2.10 Training-label distribution",
        "",
        provenance_table(provenance),
        "",
        f"Points falling outside Jabalpur district: "
        f"{provenance.get('points_outside_jabalpur')}. "
        f"Total {provenance['total_points']} points. "
        f"{provenance['note']}",
        "",
        "## 2.5 Consensus reference audited against an independent product",
        "",
        arbiter_table(arbiter),
        "",
        "## 2.16 Hyperparameters retuned on the development districts",
        "",
        tuning_table(tuning),
        "",
    ]

    OUTPUT.write_text("\n".join(sections) + "\n")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
